services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: emofinder-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env     # Carga tus variables (sin copiarlas en la imagen)
    volumes:
      - ./backend:/app     # Monta tu código local (útil si desarrollas)
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: emofinder-frontend
    ports:
      - "5173:80"          # Sirve el frontend en el puerto 5173
    depends_on:
      - backend
    restart: unless-stopped